# Generated by Django 3.1.5 on 2021-02-08 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_productimages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimages',
            options={'verbose_name': 'Product Image', 'verbose_name_plural': 'Product Images'},
        ),
    ]
